
from prusaslicer_anti_alias_z import extract_nozzle_from_gcode

def test_extract_nozzle_from_header():
    lines = [
        "; generated by PrusaSlicer\n",
        "; nozzle_diameter = 0.6\n",
        "; layer_height = 0.25\n",
        "G90\n",
    ]
    assert extract_nozzle_from_gcode(lines) == 0.6

def test_extract_nozzle_none_when_missing():
    lines = [
        "; generated by PrusaSlicer\n",
        "; layer_height = 0.25\n",
        "G90\n",
    ]
    assert extract_nozzle_from_gcode(lines) is None
